//! Config file generation for `plit init`.
//!
//! Generates two files:
//! - `~/.config/plit/config.json` — gateway configuration
//! - `~/.config/plit/.env` — Pipelit environment variables

use std::collections::HashMap;
use std::path::PathBuf;

use anyhow::{Context, Result};
use serde::Serialize;

use super::prereqs::Environment;
use super::prompts::UserInputs;
use super::tokens::SharedTokens;
use crate::output;

// ---------------------------------------------------------------------------
// Gateway config structure (subset matching config.example.json)
// ---------------------------------------------------------------------------

#[derive(Serialize)]
struct GatewayConfig {
    gateway: GatewaySection,
    backends: HashMap<String, BackendEntry>,
    auth: AuthSection,
    credentials: HashMap<String, serde_json::Value>,
}

#[derive(Serialize)]
struct GatewaySection {
    listen: String,
    admin_token: String,
    default_backend: String,
    adapters_dir: String,
    adapter_port_range: [u16; 2],
}

#[derive(Serialize)]
struct BackendEntry {
    protocol: String,
    inbound_url: String,
    token: String,
    active: bool,
}

#[derive(Serialize)]
struct AuthSection {
    send_token: String,
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Return the plit config directory (`~/.config/plit/`).
pub fn config_dir() -> Result<PathBuf> {
    let base = dirs::config_dir().context("Could not determine config directory")?;
    Ok(base.join("plit"))
}

/// Return the plit data directory (`~/.local/share/plit/`).
pub fn data_dir() -> Result<PathBuf> {
    let base = dirs::data_local_dir().context("Could not determine data directory")?;
    Ok(base.join("plit"))
}

/// Path to the gateway config file.
pub fn config_json_path() -> Result<PathBuf> {
    Ok(config_dir()?.join("config.json"))
}

/// Path to the Pipelit .env file.
pub fn dot_env_path() -> Result<PathBuf> {
    Ok(config_dir()?.join(".env"))
}

/// Path to the Pipelit clone directory.
pub fn pipelit_dir() -> Result<PathBuf> {
    Ok(data_dir()?.join("pipelit"))
}

/// Path to the Python virtualenv.
pub fn venv_dir() -> Result<PathBuf> {
    Ok(data_dir()?.join("venv"))
}

pub fn write_configs(inputs: &UserInputs, tokens: &SharedTokens, env: &Environment) -> Result<()> {
    let cfg_dir = config_dir()?;
    std::fs::create_dir_all(&cfg_dir)
        .with_context(|| format!("Failed to create config directory: {}", cfg_dir.display()))?;

    write_gateway_config(inputs, tokens)?;
    write_dot_env(inputs, tokens, env)?;

    Ok(())
}

/// Write `~/.config/plit/config.json`.
fn write_gateway_config(inputs: &UserInputs, tokens: &SharedTokens) -> Result<()> {
    let data = data_dir()?;
    let adapters_dir = data.join("pipelit").join("adapters");

    let mut backends = HashMap::new();
    backends.insert(
        "pipelit".to_string(),
        BackendEntry {
            protocol: "pipelit".to_string(),
            inbound_url: format!("http://localhost:{}/api/v1/inbound", inputs.pipelit_port),
            token: tokens.inbound_token.clone(),
            active: true,
        },
    );

    let config = GatewayConfig {
        gateway: GatewaySection {
            listen: format!("127.0.0.1:{}", inputs.gateway_port),
            admin_token: tokens.admin_token.clone(),
            default_backend: "pipelit".to_string(),
            adapters_dir: adapters_dir.to_string_lossy().to_string(),
            adapter_port_range: [9000, 9100],
        },
        backends,
        auth: AuthSection {
            send_token: tokens.send_token.clone(),
        },
        credentials: HashMap::new(),
    };

    let path = config_json_path()?;
    let json =
        serde_json::to_string_pretty(&config).context("Failed to serialize gateway config")?;
    std::fs::write(&path, &json).with_context(|| format!("Failed to write {}", path.display()))?;
    restrict_permissions(&path)?;

    output::status(&format!("  ✓ Wrote {}", path.display()));
    Ok(())
}

fn write_dot_env(inputs: &UserInputs, tokens: &SharedTokens, env: &Environment) -> Result<()> {
    let data = data_dir()?;
    let db_path = data.join("pipelit.db");
    let secret_key = uuid::Uuid::new_v4().to_string();

    let content = format!(
        "\
# Pipelit environment — generated by plit init
DATABASE_URL=sqlite:///{db_path}
SECRET_KEY={secret_key}
DEBUG=false
ALLOWED_HOSTS=localhost,127.0.0.1

# Sandbox
SANDBOX_MODE={sandbox_mode}

# Gateway integration
GATEWAY_ENABLED=true
GATEWAY_URL=http://localhost:{gw_port}
GATEWAY_ADMIN_TOKEN={admin_token}
GATEWAY_SEND_TOKEN={send_token}
GATEWAY_INBOUND_TOKEN={inbound_token}
",
        db_path = db_path.display(),
        secret_key = secret_key,
        sandbox_mode = env.sandbox_mode,
        gw_port = inputs.gateway_port,
        admin_token = tokens.admin_token,
        send_token = tokens.send_token,
        inbound_token = tokens.inbound_token,
    );

    let path = dot_env_path()?;
    std::fs::write(&path, &content)
        .with_context(|| format!("Failed to write {}", path.display()))?;
    restrict_permissions(&path)?;

    output::status(&format!("  ✓ Wrote {}", path.display()));
    Ok(())
}

#[cfg(unix)]
fn restrict_permissions(path: &std::path::Path) -> Result<()> {
    use std::os::unix::fs::PermissionsExt;
    std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o600))
        .with_context(|| format!("Failed to set permissions on {}", path.display()))
}

#[cfg(not(unix))]
fn restrict_permissions(_path: &std::path::Path) -> Result<()> {
    Ok(())
}
